unit GameObjects65;

interface

procedure LoadGameObjects65;

implementation

uses
  Responses;

procedure LoadGameObjects65;
var
  id: longint;
begin

  id:=82136;
  GameObjectTPL[id].Entry:=82136;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=731;
  GameObjectTPL[id].Name[0]:='Lamppost';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=82137;
  GameObjectTPL[id].Entry:=82137;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=731;
  GameObjectTPL[id].Name[0]:='Lamppost';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=82138;
  GameObjectTPL[id].Entry:=82138;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=731;
  GameObjectTPL[id].Name[0]:='Lamppost';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=82139;
  GameObjectTPL[id].Entry:=82139;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=731;
  GameObjectTPL[id].Name[0]:='Lamppost';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=82140;
  GameObjectTPL[id].Entry:=82140;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=731;
  GameObjectTPL[id].Name[0]:='Lamppost';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

end;

end.

