unit GameObjects78;

interface

procedure LoadGameObjects78;

implementation

uses
  Responses;

procedure LoadGameObjects78;
var
  id: longint;
begin

  id:=98343;
  GameObjectTPL[id].Entry:=98343;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='War Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98347;
  GameObjectTPL[id].Entry:=98347;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='Trade Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98348;
  GameObjectTPL[id].Entry:=98348;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='Trade Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98349;
  GameObjectTPL[id].Entry:=98349;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='War Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98350;
  GameObjectTPL[id].Entry:=98350;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='Trade Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98351;
  GameObjectTPL[id].Entry:=98351;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='Magic Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=98354;
  GameObjectTPL[id].Entry:=98354;
  GameObjectTPL[id].TypeID:=5;
  GameObjectTPL[id].DisplayID:=663;
  GameObjectTPL[id].Name[0]:='Trade Quarter';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=1;
  GameObjectTPL[id].Param[1]:=1;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

end;

end.

