unit Creatures40;

interface

procedure LoadCreatures40;

implementation

uses
  Responses;

procedure LoadCreatures40;
var
  id: longint;
begin

  id:=39010;
  CreatureTPL[id].Entry:=39010;
  CreatureTPL[id].Name[0]:='RUS:Martyr Stalker (Reputation)';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=1088;
  CreatureTPL[id].TypeID:=10;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=3;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=169;
  CreatureTPL[id].DisplayID[1]:=11686;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=0.000100;
  CreatureTPL[id].Unk4:=1.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;

  id:=39172;
  CreatureTPL[id].Entry:=39172;
  CreatureTPL[id].Name[0]:='RUS:Marshal Magruder';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='RUS:Intendant Ledyanykh Okov';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=0;
  CreatureTPL[id].TypeID:=7;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=0;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=31346;
  CreatureTPL[id].DisplayID[1]:=0;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=1.000000;
  CreatureTPL[id].Unk4:=1.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;

  id:=39173;
  CreatureTPL[id].Entry:=39173;
  CreatureTPL[id].Name[0]:='RUS:Chempion Ros''slay';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='RUS:Intendant Ledyanykh Okov';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=0;
  CreatureTPL[id].TypeID:=7;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=0;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=31347;
  CreatureTPL[id].DisplayID[1]:=0;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=1.000000;
  CreatureTPL[id].Unk4:=1.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;

  id:=39372;
  CreatureTPL[id].Entry:=39372;
  CreatureTPL[id].Name[0]:='RUS:Garrosh Adskiy Krik';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='RUS:Predvoditel'' armii Pesni Voyny';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=4;
  CreatureTPL[id].TypeID:=7;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=1;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=31428;
  CreatureTPL[id].DisplayID[1]:=0;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=400.000000;
  CreatureTPL[id].Unk4:=10.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;

  id:=39509;
  CreatureTPL[id].Entry:=39509;
  CreatureTPL[id].Name[0]:='RUS:Aronen';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='RUS:Uchenik Orma';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=0;
  CreatureTPL[id].TypeID:=7;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=0;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=31474;
  CreatureTPL[id].DisplayID[1]:=0;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=1.000000;
  CreatureTPL[id].Unk4:=1.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;

  id:=39509;
  CreatureTPL[id].Entry:=39509;
  CreatureTPL[id].Name[0]:='RUS:Aronen';
  CreatureTPL[id].Name[1]:='';
  CreatureTPL[id].Name[2]:='';
  CreatureTPL[id].Name[3]:='';
  CreatureTPL[id].GuildName:='RUS:Uchenik Orma';
  CreatureTPL[id].AssistName:='';
  CreatureTPL[id].Flags:=0;
  CreatureTPL[id].TypeID:=7;
  CreatureTPL[id].Family:=0;
  CreatureTPL[id].Rank:=0;
  CreatureTPL[id].Unk1:=0;
  CreatureTPL[id].SpellDataID:=0;
  CreatureTPL[id].DisplayID[0]:=31474;
  CreatureTPL[id].DisplayID[1]:=0;
  CreatureTPL[id].DisplayID[2]:=0;
  CreatureTPL[id].DisplayID[3]:=0;
  CreatureTPL[id].Unk3:=1.000000;
  CreatureTPL[id].Unk4:=1.000000;
  CreatureTPL[id].Civilian:=0;
  CreatureTPL[id].Unk5_1:=0;
  CreatureTPL[id].Unk5_2:=0;
  CreatureTPL[id].Unk5_3:=0;
  CreatureTPL[id].Unk5_4:=0;
  CreatureTPL[id].Unk6:=0;
  CreatureTPL[id].Unk7:=0;
  CreatureTPL[id].Unk8:=0;
  CreatureTPL[id].GossipID:=0;
  CreatureTPL[id].Greetings:='';
  CreatureTPL[id].EmoteID:=0;
  CreatureTPL[id].EmoteDelay:=0;
end;

end.

