unit GameObjects25;

interface

procedure LoadGameObjects25;

implementation

uses
  Responses;

procedure LoadGameObjects25;
var
  id: longint;
begin

  id:=26449;
  GameObjectTPL[id].Entry:=26449;
  GameObjectTPL[id].TypeID:=10;
  GameObjectTPL[id].DisplayID:=231;
  GameObjectTPL[id].Name[0]:='Recombobulator';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Name[5]:='';
  GameObjectTPL[id].Name[6]:='';
  GameObjectTPL[id].Param[0]:=0;
  GameObjectTPL[id].Param[1]:=0;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=1;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;
  GameObjectTPL[id].ParamFloat:=0.000000;

  id:=26494;
  GameObjectTPL[id].Entry:=26494;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=197;
  GameObjectTPL[id].Name[0]:='Dwarven Brazier';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Name[5]:='';
  GameObjectTPL[id].Name[6]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;
  GameObjectTPL[id].ParamFloat:=0.000000;

  id:=26495;
  GameObjectTPL[id].Entry:=26495;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=197;
  GameObjectTPL[id].Name[0]:='Dwarven Brazier';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Name[5]:='';
  GameObjectTPL[id].Name[6]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;
  GameObjectTPL[id].ParamFloat:=0.000000;

  id:=26496;
  GameObjectTPL[id].Entry:=26496;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=197;
  GameObjectTPL[id].Name[0]:='Dwarven Brazier';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Name[5]:='';
  GameObjectTPL[id].Name[6]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=2061;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;
  GameObjectTPL[id].ParamFloat:=0.000000;

  id:=26499;
  GameObjectTPL[id].Entry:=26499;
  GameObjectTPL[id].TypeID:=8;
  GameObjectTPL[id].DisplayID:=197;
  GameObjectTPL[id].Name[0]:='Dwarven Brazier';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Name[5]:='';
  GameObjectTPL[id].Name[6]:='';
  GameObjectTPL[id].Param[0]:=4;
  GameObjectTPL[id].Param[1]:=10;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=0;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=0;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=0;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;
  GameObjectTPL[id].ParamFloat:=0.000000;

end;

end.

