unit GameObjects62;

interface

procedure LoadGameObjects62;

implementation

uses
  Responses;

procedure LoadGameObjects62;
var
  id: longint;
begin

  id:=75293;
  GameObjectTPL[id].Entry:=75293;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Battered Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=57;
  GameObjectTPL[id].Param[1]:=4073;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75295;
  GameObjectTPL[id].Entry:=75295;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Iron Bound Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=5;
  GameObjectTPL[id].Param[1]:=4074;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75296;
  GameObjectTPL[id].Entry:=75296;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Iron Bound Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=24;
  GameObjectTPL[id].Param[1]:=4076;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75297;
  GameObjectTPL[id].Entry:=75297;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Iron Bound Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=60;
  GameObjectTPL[id].Param[1]:=4077;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75298;
  GameObjectTPL[id].Entry:=75298;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Solid Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=57;
  GameObjectTPL[id].Param[1]:=4074;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75299;
  GameObjectTPL[id].Entry:=75299;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Solid Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=57;
  GameObjectTPL[id].Param[1]:=4076;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

  id:=75300;
  GameObjectTPL[id].Entry:=75300;
  GameObjectTPL[id].TypeID:=3;
  GameObjectTPL[id].DisplayID:=259;
  GameObjectTPL[id].Name[0]:='Large Solid Chest';
  GameObjectTPL[id].Name[1]:='';
  GameObjectTPL[id].Name[2]:='';
  GameObjectTPL[id].Name[3]:='';
  GameObjectTPL[id].Name[4]:='';
  GameObjectTPL[id].Param[0]:=57;
  GameObjectTPL[id].Param[1]:=4077;
  GameObjectTPL[id].Param[2]:=0;
  GameObjectTPL[id].Param[3]:=1;
  GameObjectTPL[id].Param[4]:=0;
  GameObjectTPL[id].Param[5]:=0;
  GameObjectTPL[id].Param[6]:=0;
  GameObjectTPL[id].Param[7]:=0;
  GameObjectTPL[id].Param[8]:=0;
  GameObjectTPL[id].Param[9]:=0;
  GameObjectTPL[id].Param[10]:=1;
  GameObjectTPL[id].Param[11]:=0;
  GameObjectTPL[id].Param[12]:=1;
  GameObjectTPL[id].Param[13]:=0;
  GameObjectTPL[id].Param[14]:=0;
  GameObjectTPL[id].Param[15]:=0;
  GameObjectTPL[id].Param[16]:=0;
  GameObjectTPL[id].Param[17]:=0;
  GameObjectTPL[id].Param[18]:=0;
  GameObjectTPL[id].Param[19]:=0;
  GameObjectTPL[id].Param[20]:=0;
  GameObjectTPL[id].Param[21]:=0;
  GameObjectTPL[id].Param[22]:=0;
  GameObjectTPL[id].Param[23]:=0;

end;

end.

